baseURL = "https://www.rohan20k.github.io"
languageCode = "en-us"
title = "Rohan Khurana"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "Hello I'm Rohan Khurana"
author = "Rohan Khurana"
description = "Graduate Student ● Data Science ● Software Development"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/rohankhurana"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/rohan20k"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:rohan20k@uw.edu"

[[params.socialIcons]]
icon = "fa-download"
title = "resume"
href = 'resume/Rohan_Khurana_Resume_New.pdf'

## Menu items

[menu]


  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Experience"
  identifier = "experience"
  weight = 200
  url = "/experience"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/post/"

  [[menu.main]]
  name = "Blogs"
  weight = 400
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Resume"
  weight = 500
  identifier = "resume"
  url = "/resume/Rohan_Khurana_Resume_New.pdf"


